# Generated by Django 5.0.6 on 2024-05-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0002_userregistermodel_user_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginStatusModel',
        ),
    ]
