# Generated by Django 5.0.6 on 2024-05-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0003_delete_loginstatusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistermodel',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
