# Generated by Django 5.0.6 on 2024-05-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0013_poll_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.poll')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pollapp.userregistermodel')),
            ],
        ),
    ]
